stepdefinitions:
  - buildproject: &buildproject
      name: Build
      image: node:8.11.4-jessie
      caches:
        - node
      artifacts:
        - "build/**"
      script:
        - npm install
        - npm run build
          #  - deploystaging: &deploystaging
          #      name: Deploy to staging S3
          #      image: garland/aws-cli-docker
          #      script:
          #        - aws s3 sync ./build/ s3://slush-web-app-staging/ --acl public-read
          #        - aws s3 sync ./server/api/ s3://slush-web-app-staging/api/ --acl public-read
          #        - aws s3 website s3://slush-web-app-staging/ --index-document index.html --error-document error.html
  - deployproduction: &deployproduction
      name: Deploy to production S3
      image: garland/aws-cli-docker
      trigger: manual
      script:
        - aws s3 sync ./build/ s3://$AWS_PRODUCTION_BUCKET/ --acl public-read
        - aws s3 website s3://$AWS_PRODUCTION_BUCKET/ --index-document index.html --error-document error.html


pipelines:
  branches:
    #    staging:
    #      - step: *buildproject
    #      - step: *deploystaging
    master:
      - step: *buildproject
      - step: *deployproduction
