export const LOAD_RESOURCE = 'oodi/Home/LOAD_RESOURCE';
export const LOAD_RESOURCE_COMPLETED = 'oodi/Home/LOAD_RESOURCE_COMPLETED';
export const LOAD_RESOURCE_ERROR = 'oodi/Home/LOAD_RESOURCE_ERROR';
