// Can be used to automatically create repetitive categories.
function makeData(template, count) {
  return Array.from({ length: count })
    .map((val, i) => i + 1)
    .map(item => ({
      ...template,
      id: `${template.id}${item}`,
      name: `${template.name} ${item}`,
    }));
}

export default [
  {
    category: 'Oppimistilat',
    id: 'o1',
    name: 'Oppimistila 1',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'Oppimistilat',
    id: 'o2',
    name: 'Oppimistila 2',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'Oppimistilat',
    id: 'av5k7ixqvzha',
    name: 'Keittiö',
    useRespa: true,
    available: 'available',
  },

  {
    category: 'Ryhmätilat',
    id: 'av5k4vxjxyha',
    name: 'Ryhmätila 1',
    useRespa: true,
    available: 'available',
  },
  {
    category: 'Ryhmätilat',
    id: 'av5k5ip53e2q',
    name: 'Ryhmätila 2',
    useRespa: true,
    available: 'available',
  },
  {
    category: 'Ryhmätilat',
    id: 'av5k5ksofidq',
    name: 'Ryhmätila 3',
    useRespa: true,
    available: 'available',
  },
  {
    category: 'Ryhmätilat',
    id: 'av5k5mveypsa',
    name: 'Ryhmätila 4',
    useRespa: true,
    available: 'available',
  },
  {
    category: 'Ryhmätilat',
    id: 'av5k57wpbdza',
    name: 'Ryhmätila 5',
    useRespa: true,
    available: 'available',
  },
  {
    category: 'Ryhmätilat',
    id: 'av5k6ayouzga',
    name: 'Ryhmätila 6',
    useRespa: true,
    available: 'available',
  },
  {
    category: 'Ryhmätilat',
    id: 'av5k6dfiu3va',
    name: 'Ryhmätila 7',
    useRespa: true,
    available: 'available',
  },
  {
    category: 'Ryhmätilat',
    id: 'av5k6eqxl4za',
    name: 'Ryhmätila 8',
    useRespa: true,
    available: 'available',
  },
  {
    category: 'Ryhmätilat',
    id: 'av5k6g75os4q',
    name: 'Ryhmätila 9',
    useRespa: true,
    available: 'available',
  },
  {
    category: 'Ryhmätilat',
    id: 'av5k6h56ne7q',
    name: 'Ryhmätila 10',
    useRespa: true,
    available: 'available',
  },
  {
    category: 'Studiot',
    id: 's1',
    name: 'Studio 1',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'Studiot',
    id: 's2',
    name: 'Studio 2',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'Studiot',
    id: 's3',
    name: 'Studio 3',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'Studiot',
    id: 's4',
    name: 'Studio 4',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'Studiot',
    id: 's5',
    name: 'Studio 5',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'Studiot',
    id: 's6',
    name: 'Studio 6',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'Pelitilat',
    id: 'p1',
    name: 'Pelitila 1',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'Pelitilat',
    id: 'p2',
    name: 'Pelitila 2',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'Pelitilat',
    id: 'p3',
    name: 'Pelitila 3',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'Pelitilat',
    id: 'p4',
    name: 'Retropelinurkka',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'Pelitilat',
    id: 'p5',
    name: 'Pelisali',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'Muut tilat',
    id: 'k',
    name: 'Kopiointi',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'Muut tilat',
    id: 'kuutio',
    name: 'Kuutio',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'Muut tilat',
    id: 'lukusali',
    name: 'Lukusali',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'Muut tilat',
    id: 'workingArea',
    name: 'Työskentelyalue',
    useRespa: false,
    available: 'nodata',
  },
  ...makeData(
    {
      category: 'workingSpace',
      id: 'wp',
      name: 'Työskentelyalue',
      useRespa: false,
      available: 'nodata',
    },
    6,
  ),
  {
    category: 'computer',
    id: 'computer1',
    name: 'Mediatietokoneet 1-18',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'computer',
    id: 'computer2',
    name: 'Asiakastietokoneet 1-14',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'machineRoom',
    id: 'mr1',
    name: 'Konehuone',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'urbanWorkshop',
    id: 'uw1',
    name: '3D tulostin 4kpl',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'urbanWorkshop',
    id: 'uw2',
    name: 'Ompelukoneet',
    useRespa: false,
    available: 'nodata',
  },
  {
    category: 'urbanWorkshop',
    id: 'uw3',
    name: 'Suurkuvatulostin ja leikkuri',
    useRespa: false,
    available: 'nodata',
  },
];
